// nextjs-approuter/app/components/Nav.tsx
'use client'

import React, { ChangeEvent, FC, FormEvent, useState } from 'react'
import { User } from '@/app/types'
import useUser from '@/app/hooks/useUser'
const LoginForm: FC<{ defaultUser: User | undefined }> = ({ defaultUser }) => {
  const { login, logout, user } = useUser(defaultUser)
  const [formData, setFormData] = useState({
    email: '',
    password: '',
  })

  const disableLogin = !formData.email || !formData.password

  const handleChange = (e: ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target
    setFormData({
      ...formData,
      [name]: value,
    })
  }

  const handleLogin = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault()
    if (!disableLogin) {
      login(formData)
    }
  }

  const handleLogout = () => {
    logout()
  }

  return (
    <div className='d-flex p-4 flex-row justify-content-end'>
      {user ? (
        <button onClick={handleLogout} className='btn btn-link'>
          Logout
        </button>
      ) : (
        <form className='d-flex flex-row gap-4' onSubmit={handleLogin}>
          <input
            type='email'
            className='form-control'
            id='email'
            name='email'
            placeholder='Username'
            value={formData.email}
            onChange={handleChange}
            required
          />
          <input
            placeholder='Password'
            type='password'
            className='form-control'
            id='password'
            name='password'
            value={formData.password}
            onChange={handleChange}
            required
          />
          <button
            disabled={disableLogin}
            type='submit'
            className='btn btn-primary'
          >
            Login
          </button>
        </form>
      )}
    </div>
  )
}

export default LoginForm

// svelte/src/routes/Nav.svelte
<script>
    import { user } from "$lib/store/user-store";
    import Cookies from "js-cookie";
    import flagsmith from "flagsmith-es/isomorphic";
    let userValue;
    function logout() {
        Cookies.remove("user", {path:"/"})
        user.set(null)
        flagsmith.logout()
    }
    user.subscribe((value) => {
        userValue= value;
    })
</script>

<header>
    <div class='d-flex p-4 flex-row justify-content-end'>
        {#if userValue}
            <button on:click={logout} class='btn btn-link'>
                Logout
            </button>
        {:else}
            <form method="POST" action="?/login" class='d-flex flex-row gap-4'>
                <input
                        type='email'
                        class='form-control'
                        id='email'
                        name='email'
                        value="flagsmith_sample_user@example.com"
                        placeholder='Username'
                        required
                />
                <input
                        placeholder='Password'
                        type='password'
                        class='form-control'
                        id='password'
                        name='password'
                        value="Password"
                        required
                />
                <button
                        type='submit'
                        class='btn btn-primary'
                >
                    Login
                </button>
            </form>
        {/if}
    </div>
</header>
