// svelte/src/routes/WelcomeMessage.svelte
<script lang="ts">
	import {flagsStore} from "$lib/store/flags-store";
	import flagsmith from "flagsmith-es/isomorphic";
	let font_size;
	flagsStore.subscribe(()=>{
		font_size = flagsmith.getValue("font_size")
	})
</script>

<div class='border border-1 rounded border-secondary p-2'>
	<code>font_size: {font_size}</code>
</div>

// nextjs-approuter/app/components/WelcomeMessage.tsx
import { FC } from 'react'
import { useFlags } from 'flagsmith/react'

type WelcomeMessageType = {}

const WelcomeMessage: FC<WelcomeMessageType> = ({}) => {
  const { welcome_message } = useFlags(['welcome_message'])
  if (!welcome_message.enabled) {
    return null
  }
  return (
    <div className='border border-1 rounded border-secondary p-2'>
      <code>{welcome_message.value}</code>
    </div>
  )
}

export default WelcomeMessage
